### ISSUE TITLE
Issues with BUILDDIR that does not match the one used in official packages

### ISSUE THREAD

**Issue by networkException** [archlinux/archlinux-repro#104]
I tried reproducing a package that has been built by [OBS](https://openbuildservice.org/) which uses [`/usr/src/packages/BUILD` as the `$BUILDDIR`](https://github.com/openSUSE/obs-build/blob/998bf9678f41b2fb62d94e2b16a92cbb39fa5845/build-recipe-arch#L37). This failed with

```
==> ERROR: Failed to create the directory $BUILDDIR (/usr/src/packages/BUILD).
    Aborting...
```

**Comment by Foxboron** [comment]
repro doesn't support random buildwrappers. It's intended to rebuild packages built with the official `devtools` and any future ways the Arch Linux packagers distribute packages.

Unless you personally want to try add support for OBS I'd rather close this issue.

**Comment by networkException** [comment]
Alright

**Comment by Foxboron** [comment]
It might be better to try have the OBS build mimic the ways `devtools` build packages. I understand why you want this (ungoogled-chromium) but I fear allowing more build stuff outside of `devtools` is going to give us quite a few headaces sadly.

**Comment by networkException** [comment]
That actually makes a lot more sense, thanks for the idea! I will look into getting this changed in OBS then
