### ISSUE TITLE
Plans/Ideas for the tool

### ISSUE THREAD

**Issue by Foxboron** [archlinux/archlinux-repro#15]
Features:
- Rebuild packages based on `.BUILDINFO`
- Build a package N times with different environments, compare builds
- Config directory with profiles/config files to change the build environment

Commands could be:
`repro` - Build package two times and compare (default)
`<reposetory>-repro` `extra-repro` `testing-repro` etc. repository to use when building
`repor check *.tar.gz` - Rebuild package based on `.BUILDINFO`

Switches:
- `--random-profiles=4`

**Comment by Foxboron** [comment]
CC @jelly @SantiagoTorres

**Comment by jelly** [comment]
I don't have an broad idea yet, currently I just want to abuse this tool for development purposes i.e. reproducing what the jenkins slave does. So I can write patches and test them. :)

**Comment by Foxboron** [comment]
```kpcyrd  : As far as I understood, we'd need commands that are able to 1) build a package with a SOURCE_DATE_EPOCH passed as an argument 2) download+verify+install packages from the archive based on a BUILDINFO file 3) acquire the correct PKGBUILD based on a version passed as an argument```
