### ISSUE TITLE
Remove hardcoded mirror/bootstrap url

### ISSUE THREAD

**Issue by jelly** [archlinux/archlinux-repro#25]
Either we read the mirror from /etc/pacman.d/mirrorlist or use pacconf and use this as this is what the user expects. On non-arch systems we could default to https://www.archlinux.org/mirrors/kernel.org/

**Comment by Foxboron** [comment]
We read a configuration file that will override the hardcoded values in the script.

https://github.com/archlinux/archlinux-repro/blob/master/docs/repro.conf.5.txt
