### ISSUE TITLE
Reproduce a package from the repository

### ISSUE THREAD

**Issue by jelly** [archlinux/archlinux-repro#26]
This tool currently can detect reproducible build issue, but it does not reproducible packages from our repo yet. For that it requires either a BUILDINFO (or extract from pkg.tar.xz) and a PKGBUILD.

This means, we need to create a chroot:

- [x] Install all old packages (installed =). pacman -U -r ? Can't use daily repo since packages can be updated twice a day!
- [x] Modify makepkg.conf for possible passed variables (options/buildenv)
- [x] Set builddir
- [x] Set builddate

**Comment by max-baz** [comment]
I think `repro check *.pkg.tar.xz` is meant exactly for this, but I might be wrong

**Comment by jelly** [comment]
Indeed, I'm pretty ignorant, really should have read the code..

Although the makepkg.conf options aren't currently set yet. @Foxboron shall I make a new bugreport for that or do you want to close this one :)

**Comment by max-baz** [comment]
Just curious, what do you mean by makepkg.conf options? There is `-M` flag where you can provide a path to makepkg.conf, and I already tried using it to change PKGEXT - it worked 🙂

**Comment by jelly** [comment]
makepkg options are:

* OPTIONS=()
* BUILDENV=()

**Comment by Foxboron** [comment]
Fixed with https://github.com/archlinux/archlinux-repro/commit/5dffe47c4f4fec413341a6296c628a41161a4e4b :fireworks:
