### ISSUE TITLE
static analysis report for repro.in: found issues

### ISSUE THREAD

**Issue by coderobe** [archlinux/archlinux-repro#53]
https://github.com/archlinux/archlinux-repro/blob/34ccee16b8f6f3c9c252feb2e46ab7f6028b8d58/repro.in#L59
Don't use variables in the printf format string. Use printf "..%s.." "$foo".

---

https://github.com/archlinux/archlinux-repro/blob/34ccee16b8f6f3c9c252feb2e46ab7f6028b8d58/repro.in#L64
Don't use variables in the printf format string. Use printf "..%s.." "$foo".

---

https://github.com/archlinux/archlinux-repro/blob/34ccee16b8f6f3c9c252feb2e46ab7f6028b8d58/repro.in#L69
Don't use variables in the printf format string. Use printf "..%s.." "$foo".

---

https://github.com/archlinux/archlinux-repro/blob/34ccee16b8f6f3c9c252feb2e46ab7f6028b8d58/repro.in#L74
Don't use variables in the printf format string. Use printf "..%s.." "$foo".

---

https://github.com/archlinux/archlinux-repro/blob/34ccee16b8f6f3c9c252feb2e46ab7f6028b8d58/repro.in#L98
Use "${var:?}" to ensure this never expands to / .
Double quote to prevent globbing and word splitting.

---

https://github.com/archlinux/archlinux-repro/blob/34ccee16b8f6f3c9c252feb2e46ab7f6028b8d58/repro.in#L112
Double quote to prevent globbing and word splitting.

---

https://github.com/archlinux/archlinux-repro/blob/34ccee16b8f6f3c9c252feb2e46ab7f6028b8d58/repro.in#L120
Word is of the form "A"B"C" (B indicated). Did you mean "ABC" or "A\"B\"C"?

---

https://github.com/archlinux/archlinux-repro/blob/34ccee16b8f6f3c9c252feb2e46ab7f6028b8d58/repro.in#L134
Word is of the form "A"B"C" (B indicated). Did you mean "ABC" or "A\"B\"C"?

---

https://github.com/archlinux/archlinux-repro/blob/34ccee16b8f6f3c9c252feb2e46ab7f6028b8d58/repro.in#L150
Double quote to prevent globbing and word splitting.

---

https://github.com/archlinux/archlinux-repro/blob/34ccee16b8f6f3c9c252feb2e46ab7f6028b8d58/repro.in#L192
Double quote to prevent globbing and word splitting.

---

https://github.com/archlinux/archlinux-repro/blob/34ccee16b8f6f3c9c252feb2e46ab7f6028b8d58/repro.in#L193
Double quote to prevent globbing and word splitting.

---

https://github.com/archlinux/archlinux-repro/blob/34ccee16b8f6f3c9c252feb2e46ab7f6028b8d58/repro.in#L210
Double quote to prevent globbing and word splitting.

---

https://github.com/archlinux/archlinux-repro/blob/34ccee16b8f6f3c9c252feb2e46ab7f6028b8d58/repro.in#L211
Double quote to prevent globbing and word splitting.

---

https://github.com/archlinux/archlinux-repro/blob/34ccee16b8f6f3c9c252feb2e46ab7f6028b8d58/repro.in#L214
Double quote to prevent globbing and word splitting.

---

https://github.com/archlinux/archlinux-repro/blob/34ccee16b8f6f3c9c252feb2e46ab7f6028b8d58/repro.in#L215
Double quote to prevent globbing and word splitting.

---

https://github.com/archlinux/archlinux-repro/blob/34ccee16b8f6f3c9c252feb2e46ab7f6028b8d58/repro.in#L240
read without -r will mangle backslashes.

---

https://github.com/archlinux/archlinux-repro/blob/34ccee16b8f6f3c9c252feb2e46ab7f6028b8d58/repro.in#L253
This printf format string has no variables. Other arguments are ignored.
Possible misspelling: PACKAGER may not be assigned, but packager is.

---

https://github.com/archlinux/archlinux-repro/blob/34ccee16b8f6f3c9c252feb2e46ab7f6028b8d58/repro.in#L282
Double quote to prevent globbing and word splitting.

---

https://github.com/archlinux/archlinux-repro/blob/34ccee16b8f6f3c9c252feb2e46ab7f6028b8d58/repro.in#L284
Double quote to prevent globbing and word splitting.

---

https://github.com/archlinux/archlinux-repro/blob/34ccee16b8f6f3c9c252feb2e46ab7f6028b8d58/repro.in#L288
read without -r will mangle backslashes.
Modification of refference_build_checksum is local (to subshell caused by pipeline).

---

https://github.com/archlinux/archlinux-repro/blob/34ccee16b8f6f3c9c252feb2e46ab7f6028b8d58/repro.in#L289
Double quote to prevent globbing and word splitting.
read without -r will mangle backslashes.
Modification of other_build_checksum is local (to subshell caused by pipeline).

---

https://github.com/archlinux/archlinux-repro/blob/34ccee16b8f6f3c9c252feb2e46ab7f6028b8d58/repro.in#L290
refference_build_checksum was modified in a subshell. That change might be lost.
other_build_checksum was modified in a subshell. That change might be lost.

---

https://github.com/archlinux/archlinux-repro/blob/34ccee16b8f6f3c9c252feb2e46ab7f6028b8d58/repro.in#L295
Double quote to prevent globbing and word splitting.

---

https://github.com/archlinux/archlinux-repro/blob/34ccee16b8f6f3c9c252feb2e46ab7f6028b8d58/repro.in#L325
Invalid flags are not handled. Add a *) case.

---

https://github.com/archlinux/archlinux-repro/blob/34ccee16b8f6f3c9c252feb2e46ab7f6028b8d58/repro.in#L337
Variable was used as an array but is now assigned a string.
Assigning an array to a string! Assign as array, or use * instead of @ to concatenate.

---

https://github.com/archlinux/archlinux-repro/blob/34ccee16b8f6f3c9c252feb2e46ab7f6028b8d58/repro.in#L342
Double quote to prevent globbing and word splitting.

---

https://github.com/archlinux/archlinux-repro/blob/34ccee16b8f6f3c9c252feb2e46ab7f6028b8d58/repro.in#L346
Possible misspelling: REPO_CONF may not be assigned, but REPRO_CONF is.

**Comment by Foxboron** [comment]
Fixed with https://github.com/archlinux/archlinux-repro/commit/0da9ddef46e8a12c8e134eee338e02b8f419dd4e and https://github.com/archlinux/archlinux-repro/commit/8e20d07dfca14c4b5997998256f02c81c96801e7

Fixes #52
