### ISSUE TITLE
Lock the build snapshot

### ISSUE THREAD

**Issue by kpcyrd** [archlinux/archlinux-repro#60]
Currently running `repro` while another `repro` process is running causes issues because the 2nd process fails in `create_snapshot` but still runs `remove_snapshot` afterwards while the other process is running.

Preferably the 1st process would create a lock and the 2nd process would wait until it can acquire the lock.

**Comment by Foxboron** [comment]
Implemented with https://github.com/archlinux/archlinux-repro/commit/38c42d9c62591fd233260ac557b239bd6f737ef2
