### ISSUE TITLE
buildinfo can fail in hard to debug ways

### ISSUE THREAD

**Issue by kpcyrd** [archlinux/archlinux-repro#65]
I tried to run buildinfo on a debian system and got this obscure error:
```
$ /usr/local/bin/buildinfo -ff cjdns-20.5-1-x86_64.pkg.tar.zst
/usr/local/bin/buildinfo: line 47: data["${key}"]: bad array subscript
pkgname=
pkgbase=
pkgver=
pkgbuild_sha256sum=
packager=
builddate=
builddir=
buildenv=
options=
installed=
$ 
```
after some troubleshooting it turned out zstd wasn't installed and tar failed. I would expect an error message that is pointing me towards tar.

**Comment by Foxboron** [comment]
This should be fixed with https://github.com/archlinux/archlinux-repro/commit/b739737270b69fb315a8c707bab7e8d8eaaf1392
