### ISSUE TITLE
repro only uses one core to build

### ISSUE THREAD

**Issue by kpcyrd** [archlinux/archlinux-repro#67]
I'm not sure if this is intentional, due to makepkg or due to nspawn. Having all cores available would be great when rebuilding core since it contains multiple gcc packages. :)

**Comment by Foxboron** [comment]
Two folded. `/usr/share/devtools` doesn't set it. If anything it is read from `~/.makepkg.conf` and do you want us to just set `MAKEPKG="-j$(nproc)"` by default in the container?

**Comment by FFY00** [comment]
I think repro should do the same as devtools and keep `{SRC,SRCPKG,PKG,LOG}DEST`, `MAKEFLAGS` and `PACKAGER` from the host `makepkg.conf`.

**Comment by Foxboron** [comment]
@FFY00 There is no host `makepkg.conf`. Repro does not assume an Arch LInux host, which is why it goes through the current troubles.

**Comment by FFY00** [comment]
Check in `/etc/makepkg.conf` and then `~/.makepkg.conf`. Is there anyone conflicting with us on `/etc/makepkg.conf`?

**Comment by Foxboron** [comment]
Well yes. Pacman is packaged in several distros. I'd rather supply nproc or allow `MAKEFLAGS` env variables then providing a `makepkg.conf` file

**Comment by FFY00** [comment]
Yes, and why is it not acceptable to read `/etc/makepkg.conf` if we document it?

And sorry, I messed up the order. I meant check `~/.makepkg.conf` first and then fallback to `/etc/makepkg.conf`.

**Comment by kpcyrd** [comment]
The issue of defaulting to one core is that it's going to become a common gotcha because this becomes an extra step in the setup instructions of a rebuilder. People running rebuilders shouldn't be required to have the same level of experience as packagers.

**Comment by FFY00** [comment]
If packagers can't deal with this then we are all doomed.

I am not thinking of any major reason why we couldn't read `/etc/makepkg.conf` in other distributions, at least for getting `MAKEFLAGS`. If this is really a problem then we can add a build system flag to disable this behavior.

But anyway, it isn't a big deal.

**Comment by Foxboron** [comment]
Repro isn't suppose to be used by packagers. But by users that want to reproduce their packages.

**Comment by FFY00** [comment]
Right, very well.

I still think a build system flag to enable/disable this behavior is a good solution.

But maybe we should just default to `-j$(nproc)` as a user should not be expected to edit a `makepkg.conf` to get large builds to not take forever.
