### ISSUE TITLE
Running repro in parallel

### ISSUE THREAD

**Issue by kpcyrd** [archlinux/archlinux-repro#68]
I'm trying to run repro multiple times (giving each their own `$BUILDDIRECTORY`) for mass rebuilds but I ran into issues with:
```
Failed to allocate scope: Unit root.scope already exists
```
It seems this is because repro builds in `/var/lib/repro/root`, with `root` then becoming the machine name in nspawn, which has to be unique.

**Comment by Foxboron** [comment]
Two problems here
- [x] root scope is because we havent added the `--empheral` option
- [x] How do we set a unique build directory? Both devtools and repro currently use the username for the overlays.

**Comment by FFY00** [comment]
This would also be a good improvement to devtools, repro should follow devtools.

The solution here would be to generate an unique directory, eg. `user-sdf78fse`. This directory would be removed after the build, we could also ship a timer to cleanup unlocked directories in case the process exited before the directory was removed.

**Comment by Foxboron** [comment]
I have also been contemplating just using `$$` and use the PID of the process.

**Comment by Foxboron** [comment]
Frankly, wouldn't `$USER-$$` solve this? Is there any need for a more unique name for these directories?

**Comment by FFY00** [comment]
Just `$$` works but I prefer `$USER-$$`. I don't see any drawbacks from this approach.

**Comment by Foxboron** [comment]
Implemented with https://github.com/archlinux/archlinux-repro/commit/6299e1e7aa02682e3d1db5528237df88d716b781
