### ISSUE TITLE
Handle existing snapshot

### ISSUE THREAD

**Issue by jelly** [archlinux/archlinux-repro#7]
```
Create a snapshot of '/mnt/msata/repro/root' in '/mnt/msata/repro/build1/root'
ERROR: cannot snapshot '/mnt/msata/repro/root': File exists
```

This probably needs a bash trap because the build might fail or the script might fail and we would like to clean up nicely afterwards.

**Comment by Foxboron** [comment]
Traps have been introduced and i think i have added code that solves this nicely \o/
