### ISSUE TITLE
Cannot run repro twice in a row within the same terminal

### ISSUE THREAD

**Issue by yan12125** [archlinux/archlinux-repro#82]
For example, after running `repro -ndf /var/cache/pacman/pkg/python-autobahn-20.6.2-1-x86_64.pkg.tar.zst`, running the same command in the same terminal again results in
```
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
```

Apparently the terminal is no longer attached(?) to a pts
```
$ ps | grep zsh
  62675 ?        00:00:00 zsh
```

This starts from https://github.com/archlinux/archlinux-repro/commit/7470fa8d91070f46b109efbd93dae05ef4021247 if I understand it correctly. If I remove the call setsid with
```Diff
diff --git a/repro.in b/repro.in
index 0fb6f15..b0ed006 100755
--- a/repro.in
+++ b/repro.in
@@ -208,7 +208,7 @@ install -d -o builduser -g builduser /pkgdest
 install -d -o builduser -g builduser /srcpkgdest
 install -d -o builduser -g builduser /build
 __END__
-    exec_nspawn "$build" $args setsid -f -c -w sudo -iu builduser bash -c ". /etc/profile; cd /startdir; SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH makepkg -sc --noconfirm --skippgpcheck $cmds"
+    exec_nspawn "$build" $args sudo -iu builduser bash -c ". /etc/profile; cd /startdir; SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH makepkg -sc --noconfirm --skippgpcheck $cmds"
     mkdir -p "./build"
     for pkgfile in "$BUILDDIRECTORY/$build"/pkgdest/*; do
         mv "$pkgfile" "./build/"
```

Then running `repro` multiple times in a terminal works fine. Is there a reason to keep terminal capabilities during the build? The current behavior is quite inconvenient for a modify-and-test workflow.

**Comment by Foxboron** [comment]
Need `setsid` else `autoconf` (I think)  can't detect `poll.h` capabilities as it attempts to poll `/dev/console` in the env. This is annoying, but the problem needs fixing instead of blindly removing `setsid`.

**Comment by yan12125** [comment]
I guess those check results can be adjusted with `ac_cv_foobar=yes` knobs?

**Comment by Foxboron** [comment]
Probably? But this would need to be fixed in all packages?

**Comment by yan12125** [comment]
Yep, unless autoconf/automake is patched to assume terminal capabilities are available.

**Comment by Foxboron** [comment]
Right. but this is (probably) outside of the scope of either. So this needs to be fixed with `nspawn` or something more clever.

**Comment by yan12125** [comment]
Thanks for the hint. Let me try out and see if I can keep terminal usable without affecting reproducibility of packages.

**Comment by yan12125** [comment]
I ran rebuilderd with `archlinux-core` profile and it seems none of non-reproducible packages are caused by availability of terminal capabilities. I may not continue testing other packages as it's too time consuming.

On the other hand, I think rebuilderd workers running for https://reproducible.archlinux.org/ do not allocate terminals when building packages? If so, removing setsid here should help packagers to investigate why a package is reproducible locally but not on https://reproducible.archlinux.org/.
